name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: dop_v1_f7f3efc93b12d6d0417597328b2347663a117cf6a60abe268efa5c94f553de21
      - run: doctl kubernetes cluster kubeconfig save emart
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
