name: tests-items

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd items && npm config set strict-ssl && npm install && npm run test:ci
