name: tests-orders

<<<<<<< HEAD
on: pull_request

=======
on:
  pull_request
    paths:
      - 'orders/**'
>>>>>>> main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm config set strict-ssl && npm install && npm run test:ci
