name: tests-auth

<<<<<<< HEAD
on: pull_request
=======
on:
  pull_request:
    paths:
      - 'auth/**'
>>>>>>> main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm config set strict-ssl false && npm install && npm run test:ci
