name: tests-items

<<<<<<< HEAD
on: pull_request
=======
on:
  pull_request
    paths:
      - 'items/**'
>>>>>>> main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd items && npm config set strict-ssl && npm install && npm run test:ci
