name: tests-payments

<<<<<<< HEAD
on: pull_request
=======
on:
  pull_request
    paths:
      - 'payments/**'
>>>>>>> main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm config set strict-ssl && npm install && npm run test:ci
